server: 
  port: 56085

spring:
  datasource:
    url: jdbc:mysql://39.106.196.224:56085/bank?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&useUnicode=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: agricultural-bank
  name-server: 127.0.0.1:9876