server: 
  port: 56086

spring:
  datasource:
    url: jdbc:mysql://121.36.33.154:56086/bank?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&useSSL=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: construction-bank
  name-server: 127.0.0.1:9876