server: 
  port: 56088

spring:
  datasource:
    url: jdbc:mysql://121.36.33.154:56088/bank_pay?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&useSSL=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: producer_notify_msg_pay
  name-server: 127.0.0.1:9876
