server: 
  port: 56088

spring:
  datasource:
    url: jdbc:mysql://39.106.196.224:56088/bank_pay?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&useUnicode=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: producer_notify_msg_pay
  name-server: 127.0.0.1:9876