server:
  port: 8761

spring:
  application:
    name: one

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

  server:
    enable-self-preservation: false

