server: 
  port: 56087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://39.106.196.224:56087/bank?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

rocketmq:
  producer:
    group: producer_notify_msg_bank
  name-server: 127.0.0.1:9876
