spring:
  application:
    name: agricultural-bank
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /agricultural

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

ribbon:
  eager-load:
    enabled: true
    clients: construction-bank
feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000

logging:
  level:
    root: INFO
    io:
      seata: DEBUG
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: DEBUG